version: 1.0.3
 
# branches to build
branches:
  # whitelist
  only:
    - master
 
  # blacklist
  except:
    - gh-pages
 
# Do not build on tags (GitHub only)
skip_tags: true
 
# Operating system (build VM template)
os: Windows Server 2012
 
